const level4Questions = [
  { question: "मैं बीमार नहीं हूँ।", options: ["I am not ready.", "I am not sick.", "I am not dishonest.", "I am not hungry."], correct: 1 },
  { question: "मैं तैयार नहीं हूँ।", options: ["I am not sick.", "I am not ready.", "I am not foolish.", "I am not honest."], correct: 1 },
  { question: "हमलोग बेईमान नहीं हैं।", options: ["We are not dishonest.", "We are not ready.", "We are not sick.", "We are not foolish."], correct: 0 },
  { question: "हमलोग पागल नहीं हैं।", options: ["We are not kind.", "We are not foolish.", "We are not dishonest.", "We are not ready."], correct: 1 },
  { question: "तुम भूखे नहीं हो।", options: ["You are not hungry.", "You are not sick.", "You are not foolish.", "You are not dishonest."], correct: 0 },
  { question: "तुमलोग गलत नहीं हो।", options: ["You all are not kind.", "You all are not foolish.", "You all are not wrong.", "You all are not hungry."], correct: 2 },
  { question: "आपलोग गरीब नहीं हैं।", options: ["You all are not sick.", "You all are not poor.", "You all are not dishonest.", "You all are not kind."], correct: 1 },
  { question: "वह डरपोक नहीं हैं।", options: ["He is not kind.", "He is not a coward.", "He is not foolish.", "He is not poor."], correct: 1 },
  { question: "वह अच्छी नहीं है।", options: ["She is not kind.", "She is not good.", "She is not a nurse.", "She is not ready."], correct: 1 },
  { question: "सीता कुरूप नहीं है।", options: ["Seeta is not tall.", "Seeta is not beautiful.", "Seeta is not ugly.", "Seeta is not kind."], correct: 2 },
  { question: "वे लोग मूर्ख नहीं हैं।", options: ["They are not foolish.", "They are not poor.", "They are not ready.", "They are not dishonest."], correct: 0 },
  { question: "पिताजी तैयार नहीं हैं।", options: ["Father is not ready.", "Father is not kind.", "Father is not sick.", "Father is not a teacher."], correct: 0 },
  { question: "बच्चे भूखे नहीं हैं।", options: ["The children are not good.", "The children are not hungry.", "The children are not kind.", "The children are not dishonest."], correct: 1 },
  { question: "राम और श्याम तैयार नहीं हैं।", options: ["Ram and Shyam are not ready.", "Ram and Shyam are not good.", "Ram and Shyam are not foolish.", "Ram and Shyam are not dishonest."], correct: 0 },
  { question: "मैं चोर नहीं हूँ।", options: ["I am not a student.", "I am not a thief.", "I am not ready.", "I am not foolish."], correct: 1 },
  { question: "तुम विद्यार्थी नहीं हो।", options: ["You are not a farmer.", "You are not a student.", "You are not a teacher.", "You are not a thief."], correct: 1 },
  { question: "आप एक डॉक्टर नहीं हैं।", options: ["You are not a doctor.", "You are not a teacher.", "You are not a student.", "You are not a poet."], correct: 0 },
  { question: "वह एक कलाकार नहीं है।", options: ["He is not a doctor.", "He is not a teacher.", "He is not an artist.", "He is not a farmer."], correct: 2 },
  { question: "सीता एक नर्स नहीं है।", options: ["Seeta is not a nurse.", "Seeta is not a doctor.", "Seeta is not a teacher.", "Seeta is not an artist."], correct: 0 },
  { question: "हमलोग नौकर नहीं हैं।", options: ["We are not servants.", "We are not farmers.", "We are not students.", "We are not artists."], correct: 0 },
  { question: "आपलोग किसान नहीं हैं।", options: ["You all are not students.", "You all are not teachers.", "You all are not farmers.", "You all are not servants."], correct: 2 },
  { question: "वे लोग शिक्षक नहीं हैं।", options: ["They are not students.", "They are not farmers.", "They are not teachers.", "They are not doctors."], correct: 2 },
  { question: "रामू और गोपी नेता नहीं हैं।", options: ["Ramu and Gopi are not leaders.", "Ramu and Gopi are not teachers.", "Ramu and Gopi are not farmers.", "Ramu and Gopi are not students."], correct: 0 }
];