const level2Questions = [
  { question: "वह भूखा है।", options: ["He is hungry.", "He is not hungry.", "He is rich.", "He is happy."], correct: 0 },
  { question: "वे लोग व्यस्त हैं।", options: ["They are free.", "They are busy.", "They are sad.", "They are happy."], correct: 1 },
  { question: "सीता लंबी है।", options: ["Seeta is tall.", "Seeta is short.", "Seeta is thin.", "Seeta is fat."], correct: 0 },
  { question: "मैं लंबा हूँ।", options: ["I am tall.", "I am short.", "I am happy.", "I am sad."], correct: 0 },
  { question: "वह मोटी है।", options: ["She is thin.", "She is fat.", "She is tall.", "She is poor."], correct: 1 },
  { question: "वह लंबी और मोटी है।", options: ["She is tall and thin.", "She is short and fat.", "She is tall and fat.", "She is short and thin."], correct: 2 },
  { question: "मोहन डरपोक है।", options: ["Mohan is brave.", "Mohan is coward.", "Mohan is rich.", "Mohan is sad."], correct: 1 },
  { question: "वह पागल है।", options: ["He is crazy.", "He is wise.", "He is sad.", "He is happy."], correct: 0 },
  { question: "मैं दयालु और ईमानदार हूँ।", options: ["I am kind and honest.", "I am kind and rich.", "I am sad and honest.", "I am bad."], correct: 0 },
  { question: "राम और श्याम तेज हैं।", options: ["Ram and Shyam are slow.", "Ram and Shyam are fast.", "Ram and Shyam are rich.", "Ram and Shyam are happy."], correct: 1 },
  { question: "माँ तैयार है।", options: ["Mother is ready.", "Mother is sad.", "Mother is poor.", "Mother is sick."], correct: 0 },
  { question: "पिताजी व्यस्त हैं।", options: ["Father is free.", "Father is busy.", "Father is sad.", "Father is happy."], correct: 1 },
  { question: "बच्चे भूखे हैं।", options: ["The children are hungry.", "The children are sad.", "The children are rich.", "The children are happy."], correct: 0 },
  { question: "गायें काली हैं।", options: ["The cows are black.", "The cows are white.", "The cows are brown.", "The cows are yellow."], correct: 0 },
  { question: "घोड़े अच्छे हैं।", options: ["The horses are bad.", "The horses are good.", "The horses are tall.", "The horses are rich."], correct: 1 },
  { question: "वे लोग युवा हैं।", options: ["They are old.", "They are young.", "They are rich.", "They are sad."], correct: 1 },
  { question: "तुमलोग बुरे हो।", options: ["You all are good.", "You all are bad.", "You all are happy.", "You all are rich."], correct: 1 },
  { question: "यह मीठा है।", options: ["It is sweet.", "It is bitter.", "It is sour.", "It is salty."], correct: 0 },
  { question: "यह काला है।", options: ["It is blue.", "It is red.", "It is black.", "It is yellow."], correct: 2 },
  { question: "यह भूरा है।", options: ["It is brown.", "It is green.", "It is yellow.", "It is white."], correct: 0 },
  { question: "आप धनी और स्वस्थ हैं।", options: ["You are poor and sick.", "You are rich and healthy.", "You are poor and healthy.", "You are rich and sick."], correct: 1 },
  { question: "राम और श्याम युवा और स्वस्थ हैं।", options: ["Ram and Shyam are old and unhealthy.", "Ram and Shyam are young and healthy.", "Ram and Shyam are old and sick.", "Ram and Shyam are young and sick."], correct: 1 }
];