const level6Questions = [
  { question: "क्या आप एक डॉक्टर हैं?", options: ["Are you an engineer?", "Are you a teacher?", "Are you a doctor?", "Are you a poet?"], correct: 2 },
  { question: "नहीं, मैं डॉक्टर नहीं हूँ। मैं एक अभियंता हूँ।", options: ["I am an engineer.", "I am a poet.", "I am a doctor.", "I am a teacher."], correct: 0 },
  { question: "क्या वे लोग कवि हैं?", options: ["Are they teachers?", "Are they poets?", "Are they engineers?", "Are they farmers?"], correct: 1 },
  { question: "हाँ, वे लोग कवि हैं।", options: ["They are farmers.", "They are poets.", "They are students.", "They are engineers."], correct: 1 },
  { question: "क्या आप व्यस्त हैं?", options: ["Are you free?", "Are you busy?", "Are you honest?", "Are you sick?"], correct: 1 },
  { question: "नहीं, मैं व्यस्त नहीं हूँ।", options: ["I am not busy.", "I am not tired.", "I am not free.", "I am not sick."], correct: 0 },
  { question: "क्या वह सुंदर है?", options: ["Is she kind?", "Is she beautiful?", "Is she rude?", "Is she poor?"], correct: 1 },
  { question: "क्या वह नेक है?", options: ["Is she kind?", "Is she rude?", "Is she crazy?", "Is she angry?"], correct: 0 },
  { question: "हाँ, वह नेक और सुंदर है।", options: ["She is kind and beautiful.", "She is rude and poor.", "She is kind and crazy.", "She is beautiful and honest."], correct: 0 },
  { question: "क्या वे लोग तैयार हैं?", options: ["Are they tired?", "Are they ready?", "Are they lazy?", "Are they sick?"], correct: 1 },
  { question: "वे लोग तैयार नहीं हैं।", options: ["They are not ready.", "They are not tired.", "They are not lazy.", "They are not happy."], correct: 0 },
  { question: "क्या वह घमंडी है?", options: ["Is she rude?", "Is she arrogant?", "Is she kind?", "Is she lazy?"], correct: 1 },
  { question: "वह घमंडी नहीं है।", options: ["She is not lazy.", "She is not rude.", "She is not arrogant.", "She is not crazy."], correct: 2 },
  { question: "वह नेक और विनम्र है।", options: ["She is kind and humble.", "She is rude and arrogant.", "She is wise and strong.", "She is polite and lazy."], correct: 0 },
  { question: "क्या आपलोग विद्यार्थी हैं?", options: ["Are you all students?", "Are you all teachers?", "Are you all farmers?", "Are you all poets?"], correct: 0 },
  { question: "हाँ, हमलोग विद्यार्थी हैं।", options: ["We are students.", "We are teachers.", "We are farmers.", "We are poets."], correct: 0 },
  { question: "क्या यह लाभदायक है?", options: ["Is it useful?", "Is it beautiful?", "Is it profitable?", "Is it harmful?"], correct: 2 },
  { question: "यह लाभदायक नहीं है।", options: ["It is not profitable.", "It is not useful.", "It is not beautiful.", "It is not harmful."], correct: 0 },
  { question: "यह बेकार है।", options: ["It is useless.", "It is harmful.", "It is profitable.", "It is useful."], correct: 0 },
  { question: "क्या पिताजी व्यस्त हैं?", options: ["Is father free?", "Is father busy?", "Is father tired?", "Is father sick?"], correct: 1 },
  { question: "हाँ, वे व्यस्त हैं।", options: ["He is busy.", "He is free.", "He is tired.", "He is sick."], correct: 0 }
];