const level5Questions = [
  { question: "क्या मैं दोषी हूँ?", options: ["Am I wrong?", "Am I guilty?", "Am I bad?", "Am I sick?"], correct: 1 },
  { question: "क्या मैं बुरा हूँ?", options: ["Am I good?", "Am I bad?", "Am I foolish?", "Am I guilty?"], correct: 1 },
  { question: "क्या आप तैयार हैं?", options: ["Are you kind?", "Are you wise?", "Are you ready?", "Are you guilty?"], correct: 2 },
  { question: "क्या हमलोग डरपोक हैं?", options: ["Are we cowards?", "Are we fools?", "Are we brave?", "Are we dishonest?"], correct: 0 },
  { question: "क्या वह बुद्धिमान् है?", options: ["Is he a coward?", "Is he intelligent?", "Is he brave?", "Is he foolish?"], correct: 1 },
  { question: "क्या सीता पागल है?", options: ["Is Seeta wise?", "Is Seeta foolish?", "Is Seeta crazy?", "Is Seeta kind?"], correct: 2 },
  { question: "क्या वे लोग बहादुर हैं?", options: ["Are they brave?", "Are they cowards?", "Are they kind?", "Are they dishonest?"], correct: 0 },
  { question: "क्या मदन और सुरेश दुष्ट हैं?", options: ["Are Madan and Suresh kind?", "Are Madan and Suresh wise?", "Are Madan and Suresh evil?", "Are Madan and Suresh brave?"], correct: 2 },
  { question: "क्या बच्चे नटखट हैं?", options: ["Are the children naughty?", "Are the children wise?", "Are the children lazy?", "Are the children kind?"], correct: 0 },
  { question: "क्या मैं मोटा हूँ?", options: ["Am I thin?", "Am I fat?", "Am I short?", "Am I tall?"], correct: 1 },
  { question: "क्या तुम एक डाकिया हो?", options: ["Are you a student?", "Are you a postman?", "Are you a doctor?", "Are you a farmer?"], correct: 1 },
  { question: "क्या वह नर्स है?", options: ["Is she a teacher?", "Is she a nurse?", "Is she a doctor?", "Is she an artist?"], correct: 1 },
  { question: "क्या आप एक डॉक्टर हैं?", options: ["Are you a teacher?", "Are you a doctor?", "Are you a poet?", "Are you an artist?"], correct: 1 },
  { question: "क्या वह जादूगर है?", options: ["Is he a magician?", "Is he a doctor?", "Is he a teacher?", "Is he an artist?"], correct: 0 },
  { question: "क्या हमलोग भिखारी हैं?", options: ["Are we beggars?", "Are we farmers?", "Are we students?", "Are we teachers?"], correct: 0 },
  { question: "क्या तुमलोग छात्र हो?", options: ["Are you all teachers?", "Are you all students?", "Are you all farmers?", "Are you all artists?"], correct: 1 },
  { question: "क्या वे लोग डॉक्टर हैं?", options: ["Are they farmers?", "Are they teachers?", "Are they doctors?", "Are they engineers?"], correct: 2 },
  { question: "क्या मदन और मोहन खिलाड़ी हैं?", options: ["Are Madan and Mohan leaders?", "Are Madan and Mohan players?", "Are Madan and Mohan teachers?", "Are Madan and Mohan farmers?"], correct: 1 },
  { question: "क्या आपलोग किसान हैं?", options: ["Are you all farmers?", "Are you all students?", "Are you all teachers?", "Are you all players?"], correct: 0 },
  { question: "क्या मैं चोर हूँ?", options: ["Am I a thief?", "Am I a teacher?", "Am I a student?", "Am I a player?"], correct: 0 },
  { question: "क्या आप थके हैं?", options: ["Are you tired?", "Are you lazy?", "Are you angry?", "Are you honest?"], correct: 0 },
  { question: "क्या वह बीमार है?", options: ["Is he sick?", "Is he honest?", "Is he angry?", "Is he foolish?"], correct: 0 },
  { question: "क्या वे लोग नेता हैं?", options: ["Are they players?", "Are they leaders?", "Are they teachers?", "Are they farmers?"], correct: 1 }
];