const level3Questions = [
  { question: "मैं एक लड़का हूँ।", options: ["I am a poet.", "I am a student.", "I am a boy.", "I am a teacher."], correct: 2 },
  { question: "मैं एक कवि हूँ।", options: ["I am a boy.", "I am a student.", "I am a teacher.", "I am a poet."], correct: 3 },
  { question: "मैं एक विद्यार्थी हूँ।", options: ["I am a student.", "I am a doctor.", "I am a boy.", "I am a teacher."], correct: 0 },
  { question: "आप एक किसान हैं।", options: ["You are a teacher.", "You are a doctor.", "You are a student.", "You are a farmer."], correct: 3 },
  { question: "आप एक शिक्षक हैं।", options: ["You are a doctor.", "You are a farmer.", "You are a teacher.", "You are a student."], correct: 2 },
  { question: "आप एक डॉक्टर हैं।", options: ["You are a teacher.", "You are a farmer.", "You are a student.", "You are a doctor."], correct: 3 },
  { question: "तुम एक नौकर हो।", options: ["You are a student.", "You are a servant.", "You are a poet.", "You are a teacher."], correct: 1 },
  { question: "तुम एक छात्र हो।", options: ["You are a servant.", "You are a teacher.", "You are a student.", "You are a poet."], correct: 2 },
  { question: "वह एक नर्स है।", options: ["She is a nurse.", "She is a doctor.", "She is a teacher.", "She is a student."], correct: 0 },
  { question: "वह एक कलाकार है।", options: ["He is an artist.", "He is a teacher.", "He is an engineer.", "He is a nurse."], correct: 0 },
  { question: "वह एक गायिका है।", options: ["She is a singer.", "She is a doctor.", "She is an engineer.", "She is a nurse."], correct: 0 },
  { question: "वह एक अभियंता है।", options: ["He is an artist.", "He is a doctor.", "He is an engineer.", "He is a teacher."], correct: 2 },
  { question: "वे एक शिक्षक हैं।", options: ["They are doctors.", "They are students.", "They are farmers.", "They are teachers."], correct: 3 },
  { question: "राम एक नेता है।", options: ["Ram is a farmer.", "Ram is a teacher.", "Ram is a leader.", "Ram is a doctor."], correct: 2 },
  { question: "मोहन एक डाकिया है।", options: ["Mohan is a teacher.", "Mohan is a farmer.", "Mohan is a postman.", "Mohan is a doctor."], correct: 2 },
  { question: "राम और मोहन किसान हैं।", options: ["Ram and Mohan are teachers.", "Ram and Mohan are engineers.", "Ram and Mohan are farmers.", "Ram and Mohan are doctors."], correct: 2 },
  { question: "तुमलोग विद्यार्थी हो।", options: ["You all are students.", "You all are doctors.", "You all are teachers.", "You all are farmers."], correct: 0 },
  { question: "आपलोग डॉक्टर हैं।", options: ["You all are students.", "You all are teachers.", "You all are doctors.", "You all are farmers."], correct: 2 },
  { question: "हमलोग शिक्षक हैं।", options: ["We all are students.", "We all are farmers.", "We all are teachers.", "We all are doctors."], correct: 2 },
  { question: "हमलोग किसान हैं।", options: ["We all are teachers.", "We all are students.", "We all are farmers.", "We all are doctors."], correct: 2 },
  { question: "वे लोग शिक्षक हैं।", options: ["They are doctors.", "They are farmers.", "They are students.", "They are teachers."], correct: 3 },
  { question: "वे लोग किसान हैं।", options: ["They are doctors.", "They are teachers.", "They are farmers.", "They are students."], correct: 2 },
  { question: "वे लोग अभियंता हैं।", options: ["They are engineers.", "They are students.", "They are farmers.", "They are teachers."], correct: 0 },
  { question: "तुमलोग छात्र हो।", options: ["You all are farmers.", "You all are students.", "You all are teachers.", "You all are doctors."], correct: 1 }
];